name: WebApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set API key
        working-directory: ./web-polling-locations
        run: |
          echo "REACT_APP_GOOGLE_MAPS_API_KEY='${{ secrets.GOOGLE_MAPS_API_KEY }}'" > .env

      - name: Install dependencies
        working-directory: ./web-polling-locations
        run: npm install

      - name: Build
        working-directory: ./web-polling-locations
        run: npm run build

      - name: Deploy to S3
        if: success()
        run: aws s3 sync ./web-polling-locations/build s3://${{ secrets.AWS_WEB_S3_BUCKET }} --delete --no-acl

      - name: Invalidate CloudFront cache
        if: success()
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
